name: letspicture
description: A photo editing app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fluro: ^1.4.0
  sqflite: ^1.1.6
  bitmap: 0.0.3
  photo_view:
    git:
      url: git://github.com/renancaraujo/photo_view.git
      ref: letspicture_compat
  niks: 0.0.3
  niks_bitmap: 0.0.1

  rxdart: 0.22.1

  image_picker: 0.5.0+9
  path_provider:
  mobx: 0.3.5
  flutter_mobx: 0.3.0+1
  after_layout: 1.0.7
  image_picker_saver: 0.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.2"
  build_runner: 1.3.1
  mobx_codegen: 0.3.3+1



flutter:
  uses-material-design: true
  assets:
    - assets/images/loading_mask.png
    - assets/images/tiny_logo.png

    # icons
    - assets/icons/streamline-icon-check@48x48.png
    - assets/icons/streamline-icon-disable@48x48.png

    # Editor icons
    - assets/icons/editor/contrast.png
    - assets/icons/editor/brightness.png
    - assets/icons/editor/saturation.png
    - assets/icons/editor/blacks.png
    - assets/icons/editor/whites.png
    - assets/icons/editor/gamma.png
    - assets/icons/editor/exposure.png

  fonts:
    - family: Exo
      fonts:
        - asset: assets/fonts/exo/Exo-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/exo/Exo-ExtraBoldItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/exo/Exo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/exo/Exo-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/exo/Exo-Bold.ttf
          weight: 700
        - asset: assets/fonts/exo/Exo-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/exo/Exo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/exo/Exo-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/exo/Exo-Medium.ttf
          weight: 500
        - asset: assets/fonts/exo/Exo-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/exo/Exo-Regular.ttf
          weight: 400
        - asset: assets/fonts/exo/Exo-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/exo/Exo-Light.ttf
          weight: 300
        - asset: assets/fonts/exo/Exo-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/exo/Exo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/exo/Exo-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/exo/Exo-Thin.ttf
          weight: 100
        - asset: assets/fonts/exo/Exo-ThinItalic.ttf
          weight: 100
          style: italic

